apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-llm-monitor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - services
  - endpoints
  - events
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.io
  resources:
  - uavmetrics
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - scheduler.io
  resources:
  - schedulingrequests
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - scheduler.io
  resources:
  - schedulingrequests/status
  verbs:
  - get
  - update
  - patch