apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uavmetrics.monitoring.io
spec:
  group: monitoring.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              node_name:
                type: string
                description: "节点名称"
              uav_id:
                type: string
                description: "无人机ID"
              gps:
                type: object
                properties:
                  latitude:
                    type: number
                  longitude:
                    type: number
                  altitude:
                    type: number
                  satellite_count:
                    type: integer
                  fix_type:
                    type: integer
              battery:
                type: object
                properties:
                  voltage:
                    type: number
                  remaining_percent:
                    type: number
                  temperature:
                    type: number
              flight:
                type: object
                properties:
                  mode:
                    type: string
                  armed:
                    type: boolean
                  ground_speed:
                    type: number
              health:
                type: object
                properties:
                  system_status:
                    type: string
                  error_count:
                    type: integer
                  warning_count:
                    type: integer
          status:
            type: object
            properties:
              last_update:
                type: string
                format: date-time
              collection_status:
                type: string
  scope: Namespaced
  names:
    plural: uavmetrics
    singular: uavmetric
    kind: UAVMetric
    shortNames:
    - uav